# Generated by Django 2.2.19 on 2021-09-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_ia_aes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iimioiaaes',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_iimioiaaes_users_+', related_query_name='+', to='base.ApiUser'),
        ),
    ]
