# Generated by Django 2.2.24 on 2022-04-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210202_1627'),
        ('passerelle_imio_ia_aes', '0002_auto_20210930_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApimsAesConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('server_url', models.CharField(help_text='URL du serveur', max_length=128, verbose_name='URL du serveur')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='Utilisateur')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Mot de passe')),
                ('aes_instance', models.CharField(blank=True, help_text='Par exemple : fleurus', max_length=128, verbose_name="Instance d'AES à contacter")),
                ('users', models.ManyToManyField(blank=True, related_name='_apimsaesconnector_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Connecteur Apims AES',
            },
        ),
        migrations.DeleteModel(
            name='IImioIaAes',
        ),
    ]
